### ISSUE TITLE
updating markdown doc on folder "projects"

### ISSUE THREAD

**Issue by Maleeha** [IALSA/ialsa-2015-portland-stencil#11]
@wibeasley  
Please note, i have a few questions about this folder that i will ask tomorrow. For now the folder and its contents have been updated in the markdown document. 
repo-files.md
< https://github.com/IALSA/ialsa-2015-portland-stencil/commit/908591c6cdb3ec16b87802f16117ee61ddb7ef3e>

**Comment by wibeasley** [comment]
I'll jot a few things to help me remember.  I'll probably edit this one post several times as I see things.
1. [Peculiars of folder "projects"](https://github.com/IALSA/ialsa-2015-portland-stencil/commit/d938f9f8b93a1f16707103d1f0b71e453ae6b16a)is a huge commit of 50 files.  Try to keep the commits small enough that you could wrap your brain around each one individually.  If a single commit requires 2 hours, it _might_ be a sign that it should have been separated into smaller commits.
2. Don't bother including the dates in the commit messages.  Think of them kinda like book or article titles.

![image](https://cloud.githubusercontent.com/assets/1372890/12468103/606cc3ea-bfa6-11e5-9fdc-e2fde0108af9.png)

**Comment by Maleeha** [comment]
@wibeasley, 
- [x] Got the _not dating the commits_ part. 
- [ ] What did you mean by keep the commits small? Because when I am constructing from the scratch, I can keep them small, But Dr. Beasely, in this particular instant, I am directly coping them from IALSA folder to the stencil. I open the documents or files to look what they are so I can do my markdown description. Do I continue the way I have been doing this or just start committing slowly over a period of time.

**Comment by wibeasley** [comment]
Instead of a single big commit of 50 files spanning ~10 different directories, _consider_ if it's conceptually cleaner to make 5 commits of 10 files each (group the commits by directory).  

This isn't an absolute rule.  Just consider if the commits would have been more coherent.  Maybe not.
