### ISSUE TITLE
Duplicate files

### ISSUE THREAD

**Issue by wibeasley** [IALSA/ialsa-2015-portland-stencil#13]
@Maleeha, be careful not to let duplicate files slip in.  For instance, delete the version of this you don't need.
- `https://github.com/IALSA/ialsa-2015-portland-stencil/blob/master/documentation/repo-files.md`
- `https://github.com/IALSA/ialsa-2015-portland-stencil/blob/master/repo-files.md`

**Comment by Maleeha** [comment]
I just deleted this one. I don't know how I created this. I will careful from here on.
- [x] Delete,  https://github.com/IALSA/ialsa-2015-portland-stencil/blob/master/repo-files.md 
  @wibeasley

**Comment by Maleeha** [comment]
@wibeasley, can I close this issue now?
