### ISSUE TITLE
Categories, constructs and measures

### ISSUE THREAD

**Issue by Maleeha** [IALSA/ialsa-2015-portland-stencil#17]
In-order to create a pre-conference survey on REDCap, i needed to know if  there was an existing document on categories, constructs and measures, that i could use to develop my questions. I asked Andrey about it and he confirmed that he had not worked on anything like that for IALSA-2015. So i am going to go ahead and do my research while i create those questions on REDCap.

**Comment by Maleeha** [comment]
@wibeasley let me know if we can close this issue, yet?

**Comment by wibeasley** [comment]
I assume you mean Andrey and not Andrea

> I am going to go ahead and do my research while i create those questions on REDCap.

Go ahead an create a file/list for the measures.  But just keep it in a csv like we sketched out last Thursday.
![image](https://cloud.githubusercontent.com/assets/1372890/13037839/1e3f1ba0-d34f-11e5-94a6-c0742d914169.png)

**Comment by wibeasley** [comment]
@Maleeha, are you sure there's not an existing list of these?  If not, here's a headstart.
https://github.com/IALSA/Portland-physical-cognitive/issues/4

**Comment by Maleeha** [comment]
@wibeasley  there are references here and there in files that I am copying over from IALSA-2015-Portland. Andrey did say he did not have a document like that when I asked him in the email. But, I will keep my eyes open.

**Comment by Maleeha** [comment]
Retreived and applied. Done!
