### ISSUE TITLE
Copying over folder 'scripts' from IALSA-2015-Portland 

### ISSUE THREAD

**Issue by Maleeha** [IALSA/ialsa-2015-portland-stencil#18]
This folder has the following:
- [x] dev
  - [x] 1a_correct_model_names.R
  - [x] x_make_pretty.R
- [x] graphs
  - [x] kb_profiles_functions.R
  - [x] main_theme.R
- [x] mplus
  - [x] prototype/
    - [x] new_b1_male_a_grip_categories_18.dgm
    - [x] new_b1_male_a_grip_categories_18.gh5
    - [x] new_b1_male_a_grip_categories_18.inp
    - [x] new_b1_male_a_grip_categories_18.out
    - [x] prototype_b1_male_a_grip_categories_18.inp
    - [x] prototype_b1_RADC.inp
  - [x] extraction_functions.R
  - [x] functions_to_generate_Mplus_scripts.R
  - [x] generate_run_graph.R
  - [x] group_variables.R
  - [x] look-at-data.R

**Comment by Maleeha** [comment]
"**scripts**" has been copied @wibeasley

**Comment by wibeasley** [comment]
@Maleeha, please change/force underscores and lowercase letters on
- any existing file that's not related to M_plus_
- any new file (including those associated M_plus_)

**Comment by Maleeha** [comment]
So @wibeasley , this goes for all folders and not just **scripts**? Also how about the input and output files associated with mplus, do I let them be as well and not change their names?

**Comment by wibeasley** [comment]
yes and yes

**Comment by Maleeha** [comment]
How about things that stand out or are generally said in a way where they use caps like REDcap? @wibeasley

**Comment by Maleeha** [comment]
Noted!

**Comment by wibeasley** [comment]
> How about things that stand out or are generally said in a way where they use caps like REDcap?

Still use lower case.

BTW, it's RED_C_ap.  The uppercase isn't really for emphasis.  It's because it stands for a word.
