### ISSUE TITLE
Copy documentation and some structure

### ISSUE THREAD

**Issue by wibeasley** [IALSA/ialsa-2015-portland-stencil#2]
@Maleeha, please start copying over files from https://github.com/IALSA/IALSA-2015-Portland.

Many things will be restructured, so that's why I don't want to blindly copy everything.  For now, just start with the things that we definite will need.  We'll need meetings with @andkov for the next few weeks, since he has a better feel for what did and didn't work well.  

Remember that a big difference between this stencil and the original repository is that now we'll try to store most of the Mplus files within the database (not the repository itself).
## Copy files such as
- READMEs
- Documentation
- Documentation images ([example](https://github.com/IALSA/IALSA-2015-Portland/blob/master/reports/model_space/figure_modelSpace5D/dashboard_tile_graph-1.png))

Consider making a new issue for groups of these files (but probably not a new issue for each file).
- [x] Remember to use checkboxes/tasks within an issue to help you keep track of the little things.
## Do **not** copy files like
- Mplus syntax files (yet).  But include their parent directories.  Create a quick readme if it doesn't exist ([example readme](https://github.com/IALSA/IALSA-2015-Portland/tree/master/reports/methodology_bivariate)).
- output files (yet).  But include their parent directories.  Create a quick readme if it doesn't exist.
- data files (yet).  But include their parent directories.  Create a quick readme if it doesn't exist.

When you're writing readmes, try to make both general and informative.  It's a tricky balancing act, but it will make it easier to create new workshop repos.
## _Probably_ copy files like (make your best guess for now)
- R and Rmd files (but not M_plus_ syntax files).
## Renaming

@andkov's and my naming conventions have changed a tad in the past year.  For file names (but not for variable names inside code), use dashes (not underscores) and only lowercase letters.

**Comment by Maleeha** [comment]
@wibeasley, starting today. Will keep working on it, but its my focus for today and tomorrow, for this week.

**Comment by Maleeha** [comment]
@andkov is removing redundant files from stencil. Every seemingly important file was copied over. Markdown document will be updated once Andrey has made those changes.
