### ISSUE TITLE
underscores to hypen in the file naming structure

### ISSUE THREAD

**Issue by Maleeha** [IALSA/ialsa-2015-portland-stencil#20]
Are we also changing all the underscores to hyphen in the file naming structure? @wibeasley

**Comment by Maleeha** [comment]
Okay so in the folder sandbox, there are a number of files with names that have underscores instead of hypen and there are a few that do not necessarily follow small letter naming convention. Is there a reason for that @andkov ? 
Also I went ahead and changed the names to the agreed upon naming convention, for most of the files. I am sorry if I was not supposed to do that. I can go back and change the names again if you would like me to? Please let me know what you want? @andkov 
@wibeasley

**Comment by Maleeha** [comment]
I am going to leave sandbox alone till I hear from you two. @andkov , @wibeasley

**Comment by Maleeha** [comment]
Also I know that i am not supposed to apply this naming convention to Mplus .inp and output files. What about R files because I have been applying the new naming convention to R files?
@wibeasley

**Comment by Maleeha** [comment]
I have applied the new naming convention to all the existing files in stencil. I still need to address them in the markdown document after you two get back to me with my inquiries. Thanks!

**Comment by wibeasley** [comment]
Changing the R files should be fine.
