### ISSUE TITLE
Math and Tennis Syllabus - (complexity of folder "studies")

### ISSUE THREAD

**Issue by Maleeha** [IALSA/ialsa-2015-portland-stencil#23]
@wibeasley @andkov 

Since you two have already been complaining about markdown, I though it was wise to ask you to please review folder **input-files** under folder **studies** in stencil. There are around a billion ( metaphorically speaking) input files on variable names and more from Mplus:
- [ ] What do you want the markdown for this to look like? 
- [ ] Do you want to add the names of all the input files in the markdown document?
- [ ] If so, what about the one line description for each of those file names?
  Please let me know so I don't go ahead and develop M & T syllabus for the next 10 generations!

Thanks

**Comment by Maleeha** [comment]
The boxes above are for me to check once I know what I need to do with this issue.

**Comment by andkov** [comment]
Don't under any .inp , .out, or .gh5 files.

**Comment by Maleeha** [comment]
In that case, mark down needs a lot of revision. I will update it this week. Thanks
