### ISSUE TITLE
document of file structure

### ISSUE THREAD

**Issue by wibeasley** [IALSA/ialsa-2015-portland-stencil#3]
@Maleeha, related to #2, create a single Markdown document that outlines the file structure of the stencil.  This will help communication between you, me, @andkov, and others.  I don't see a great location for it now.  Unless @andkov gives you a suggestion before you start, try in a root folder called `./documentation/repo-files.md`.

I don't have a create suggestion for the format of this text document, but here are [some ideas](http://stackoverflow.com/questions/19699059/representing-directory-file-structure-in-markdown-syntax).   Take your best guess for now. 

For now, maybe just a bullet list with levels.  Remember that 4 spaces is the way to tab/nest inwards.

```
* _drafts/  #*Comments/description*#
    * begin-with-the-crazy-ideas.textile
    * on-simplicity-in-technology.markdown
    * more/
        * _includes/
        * footer.html
        *  header.html
* _layouts/  #*Comments/description*#
    * default.html
    * post.html
* _config.yml
```

Your first draft doesn't have to be pretty, but we'll want it accessible later.  It will help workshop attendees get comfortable with the structure more quickly.

**Comment by Maleeha** [comment]
Markdown document will be updated once Andrey has removed all the redundant files.
