### ISSUE TITLE
File names for .ttf files

### ISSUE THREAD

**Issue by Maleeha** [IALSA/ialsa-2015-portland-stencil#32]
Just making sure, in synthesis/ there are a few sub folders with .ttf files. I am going ahead and applying the new file naming convention to it. A lot of names have capital letters in them.

**Comment by wibeasley** [comment]
I don't know what those files are.  @andkov, do they need to come over?  Or are they fairly specific to the old way?

**Comment by Maleeha** [comment]
There are also files with **.min.ttf** file extension (min one true type font file extension).

**Comment by wibeasley** [comment]
Can you send me the link so we're talking about the same location?  I'm guessing they're related to knitr's style.  If so, the do _not_ need to be moved.  Knitr will recreate them if it needs to.

**Comment by Maleeha** [comment]
https://github.com/IALSA/ialsa-2015-portland-stencil/tree/master/synthesis/bivariate_meta_files/bootstrap-2.3.2/css/fonts

@wibeasley

**Comment by Maleeha** [comment]
Also i went ahead and changed the names. I will remove them if we don't need them in stencil.

**Comment by wibeasley** [comment]
Yea, ignore anything in a bootstrap folder.  They'll be recreated automatically.

**Comment by Maleeha** [comment]
Got it. Thank you!
