### ISSUE TITLE
Issues closed/ the ones that stay put!

### ISSUE THREAD

**Issue by Maleeha** [IALSA/ialsa-2015-portland-stencil#42]
I have closed all the issues for the tasks already accomplished. The ones that are open are the ones that are either relevant or, are notes from andrey from our previous Tuesday google hangout sessions and i still need to learn from them. Most of them are logs.

**Comment by wibeasley** [comment]
Good work.  I'm going to close this issue.  Because the presence of any issue on the list implies there's something to do.  Nice work.
