### ISSUE TITLE
markdown for stencil directory

### ISSUE THREAD

**Issue by Maleeha** [IALSA/ialsa-2015-portland-stencil#6]
@wibeasley, I have completed markdown for all the updated files in stencil directory. Please have a look. Its in code.

repo-files.md
https://github.com/IALSA/ialsa-2015-portland-stencil/commit/681cf06c9b7d718fcde3df456aaf3097522d5b75
- (css at line 9), I don't know what **css** is in **libs** so there is no description for that.
- (line 15-38), Do you want description of each and every **png** in images?
- I will keep updating the markdown as I copy more files over from _IALSA-2015-portland_.

**Comment by andkov** [comment]
Css in libs customize the appearance of html produced by the rmd. Mostly, I've been using it for the menu sidebar in long reports, for enhanced navigation

**Comment by Maleeha** [comment]
Thanks @andkov. Noted!

**Comment by Maleeha** [comment]
repo-files.md
